service: batch-submit

provider:
  name: aws
  runtime: python3.7
  role: arn:aws:iam::510414441092:role/service-role/lambdaBatchRole
  timeout: 45

functions:
  stateSubmit:
    handler: handler.state_submit
    layers:
        - arn:aws:lambda:us-east-1:510414441092:layer:serverless-etl-dev-python-requirements:1
package:
    individually: true
    exclude:
        - "event.json"
        - "*.env"
        - ".env"
        - "Pipfile"
        - "Pipfile.*"
        - ".python-version"
        - ".gitignore"